# Generated by Django 5.2.7 on 2025-10-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='URL имя')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
