# Generated by Django 5.2.7 on 2025-10-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-last_name', 'first_name']},
        ),
    ]
